# .sum() definição e usabilidade

In [1]:
import pandas as pd

data = {"A": [1, 2, None, 4], "B": [None, 2, 3, 4]}
df = pd.DataFrame(data)

Cada item do dicionário representa uma coluna:

{"A": [1, 2, None, 4], "B": [None, 2, 3, 4]}

| A    | B    |
|------|------|
| 1    | None |
| 2    | 2    |
| None | 3    |
| 4    | 4    |

`display()` -> printa a tabela (dataframe)

In [2]:
display(df)

     A    B
0  1.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0

Caso eu queira mostrar o dataframe inteiro:

In [3]:
# Configurar pandas para exibir todas as linhas e colunas
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
titanic_data = pd.read_csv("./titanic.csv")
display(titanic_data)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.00,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.00,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.00,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.00,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.00,0,0,8.0500
5,0,3,Mr. James Moran,male,27.00,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.00,0,0,51.8625
7,0,3,Master. Gosta Leonard Palsson,male,2.00,3,1,21.0750
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.00,0,2,11.1333
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.00,1,0,30.0708
10,1,3,Miss. Marguerite Rut Sandstrom,female,4.00,1,1,16.7000
11,1,1,Miss. Elizabeth Bonnell,female,58.00,0,0,26.5500
12,0,3,Mr. William Henry Saundercock,male,20.00,0,0,8.0500
13,0,3,Mr. Anders Johan Andersson,male,39.00,1,5,31.2750
14,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.00,0,0,7.8542
15,1,2,Mrs. (Mary D Kingcome) Hewlett,female,55.00,0,0,16.0000
16,0,3,Master. Eugene Rice,male,2.00,4,1,29.1250
17,1,2,Mr. Charles Eugene Williams,male,23.00,0,0,13.0000
18,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.00,1,0,18.0000
19,1,3,Mrs. Fatima Masselmani,female,22.00,0,0,7.2250
20,0,2,Mr. Joseph J Fynney,male,35.00,0,0,26.0000
21,1,2,Mr. Lawrence Beesley,male,34.00,0,0,13.0000
22,1,3,Miss. Anna McGowan,female,15.00,0,0,8.0292
23,1,1,Mr. William Thompson Sloper,male,28.00,0,0,35.5000
24,0,3,Miss. Torborg Danira Palsson,female,8.00,3,1,21.0750
25,1,3,Mrs. Carl Oscar (Selma Augusta Emilia Johansso...,female,38.00,1,5,31.3875
26,0,3,Mr. Farred Chehab Emir,male,26.00,0,0,7.2250
27,0,1,Mr. Charles Alexander Fortune,male,19.00,3,2,263.0000
28,1,3,Miss. Ellen O'Dwyer,female,24.00,0,0,7.8792
29,0,3,Mr. Lalio Todoroff,male,23.00,0,0,7.8958
30,0,1,Don. Manuel E Uruchurtu,male,40.00,0,0,27.7208
31,1,1,Mrs. William Augustus (Marie Eugenie) Spencer,female,48.00,1,0,146.5208
32,1,3,Miss. Mary Agatha Glynn,female,18.00,0,0,7.7500
33,0,2,Mr. Edward H Wheadon,male,66.00,0,0,10.5000
34,0,1,Mr. Edgar Joseph Meyer,male,28.00,1,0,82.1708
35,0,1,Mr. Alexander Oskar Holverson,male,42.00,1,0,52.0000
36,1,3,Mr. Hanna Mamee,male,18.00,0,0,7.2292
37,0,3,Mr. Ernest Charles Cann,male,21.00,0,0,8.0500
38,0,3,Miss. Augusta Maria Vander Planke,female,18.00,2,0,18.0000
39,1,3,Miss. Jamila Nicola-Yarred,female,14.00,1,0,11.2417
40,0,3,Mrs. Johan (Johanna Persdotter Larsson) Ahlin,female,40.00,1,0,9.4750
41,0,2,Mrs. William John Robert (Dorothy Ann Wonnacot...,female,27.00,1,0,21.0000
42,1,2,Miss. Simonne Marie Anne Andree Laroche,female,3.00,1,2,41.5792
43,1,3,Miss. Margaret Delia Devaney,female,19.00,0,0,7.8792
44,0,3,Mr. William John Rogers,male,30.00,0,0,8.0500
45,0,3,Mr. Denis Lennon,male,20.00,1,0,15.5000
46,1,3,Miss. Bridget O'Driscoll,female,27.00,0,0,7.7500
47,0,3,Mr. Youssef Samaan,male,16.00,2,0,21.6792
48,0,3,Mrs. Josef (Josefine Franchi) Arnold-Franchi,female,18.00,1,0,17.8000
49,0,3,Master. Juha Niilo Panula,male,7.00,4,1,39.6875
50,0,3,Mr. Richard Cater Nosworthy,male,21.00,0,0,7.8000
51,1,1,Mrs. Henry Sleeper (Myna Haxtun) Harper,female,49.00,1,0,76.7292
52,1,2,Mrs. Lizzie (Elizabeth Anne Wilkinson) Faunthorpe,female,29.00,1,0,26.0000
53,0,1,Mr. Engelhart Cornelius Ostby,male,65.00,0,1,61.9792
54,1,1,Mr. Hugh Woolner,male,46.00,0,0,35.5000
55,1,2,Miss. Emily Rugg,female,21.00,0,0,10.5000
56,0,3,Mr. Mansouer Novel,male,28.50,0,0,7.2292
57,1,2,Miss. Constance Mirium West,female,5.00,1,2,27.7500
58,0,3,Master. William Frederick Goodwin,male,11.00,5,2,46.9000
59,0,3,Mr. Orsen Sirayanian,male,22.00,0,0,7.2292
60,1,1,Miss. Amelie Icard,female,38.00,0,0,80.0000
61,0,1,Mr. Henry Birkhardt Harris,male,45.00,1,0,83.4750
62,0,3,Master. Harald Skoog,male,4.00,3,2,27.9000
63,0,1,Mr. Albert A Stewart,male,64.00,0,0,27.7208
64,1,3,Master. Gerios Moubarek,male,7.00,1,1,15.2458
65,1,2,Mrs. (Elizabeth Ramell) Nye,female,29.00,0,0,10.5000
66,0,3,Mr. Ernest James Crease,male,19.00,0,0,8.1583
67,1,3,Miss. Erna Alexandra Andersson,female,17.00,4,2,7.9250
68,0,3,Mr. Vincenz Kink,male,26.00,2,0,8.6625
69,0,2,Mr. Stephen Curnow Jenkin,male,32.00,0,0,10.5000
70,0,3,Miss. Lillian Amy Goodwin,female,16.00,5,2,46.9000
71,0,2,Mr. Ambrose Jr Hood,male,21.00,0,0,73.5000
72,0,3,Mr. Apostolos Chronopoulos,male,26.00,1,0,14.4542
73,1,3,Mr. Lee Bing,male,32.00,0,0,56.4958
74,0,3,Mr. Sigurd Hansen Moen,male,25.00,0,0,7.6500
75,0,3,Mr. Ivan Staneff,male,23.00,0,0,7.8958
76,0,3,Mr. Rahamin Haim Moutal,male,28.00,0,0,8.0500
77,1,2,Master. Alden Gates Caldwell,male,0.83,0,2,29.0000
78,1,3,Miss. Elizabeth Dowdell,female,30.00,0,0,12.4750
79,0,3,Mr. Achille Waelens,male,22.00,0,0,9.0000
80,1,3,Mr. Jan Baptist Sheerlinck,male,29.00,0,0,9.5000
81,1,3,Miss. Brigdet Delia McDermott,female,31.00,0,0,7.7875
82,0,1,Mr. Francisco M Carrau,male,28.00,0,0,47.1000
83,1,2,Miss. Bertha Ilett,female,17.00,0,0,10.5000
84,1,3,Mrs. Karl Alfred (Maria Mathilda Gustafsson) B...,female,33.00,3,0,15.8500
85,0,3,Mr. William Neal Ford,male,16.00,1,3,34.3750
86,0,3,Mr. Selman Francis Slocovski,male,20.00,0,0,8.0500
87,1,1,Miss. Mabel Helen Fortune,female,23.00,3,2,263.0000
88,0,3,Mr. Francesco Celotti,male,24.00,0,0,8.0500
89,0,3,Mr. Emil Christmann,male,29.00,0,0,8.0500
90,0,3,Mr. Paul Edvin Andreasson,male,20.00,0,0,7.8542
91,0,1,Mr. Herbert Fuller Chaffee,male,46.00,1,0,61.1750
92,0,3,Mr. Bertram Frank Dean,male,26.00,1,2,20.5750
93,0,3,Mr. Daniel Coxon,male,59.00,0,0,7.2500
94,0,3,Mr. Charles Joseph Shorney,male,22.00,0,0,8.0500
95,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542
96,1,1,Mr. William Bertram Greenfield,male,23.00,0,1,63.3583
97,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34.00,0,1,23.0000
98,0,2,Mr. Sinai Kantor,male,34.00,1,0,26.0000
99,0,3,Miss. Matilda Petranec,female,28.00,0,0,7.8958
100,0,3,Mr. Pastcho Petroff,male,29.00,0,0,7.8958
101,0,1,Mr. Richard Frasar White,male,21.00,0,1,77.2875
102,0,3,Mr. Gustaf Joel Johansson,male,33.00,0,0,8.6542
103,0,3,Mr. Anders Vilhelm Gustafsson,male,37.00,2,0,7.9250
104,0,3,Mr. Stoytcho Mionoff,male,28.00,0,0,7.8958
105,1,3,Miss. Anna Kristine Salkjelsvik,female,21.00,0,0,7.6500
106,1,3,Mr. Albert Johan Moss,male,29.00,0,0,7.7750
107,0,3,Mr. Tido Rekic,male,38.00,0,0,7.8958
108,1,3,Miss. Bertha Moran,female,28.00,1,0,24.1500
109,0,1,Mr. Walter Chamberlain Porter,male,47.00,0,0,52.0000
110,0,3,Miss. Hileni Zabour,female,14.50,1,0,14.4542
111,0,3,Mr. David John Barton,male,22.00,0,0,8.0500
112,0,3,Miss. Katriina Jussila,female,20.00,1,0,9.8250
113,0,3,Miss. Malake Attalah,female,17.00,0,0,14.4583
114,0,3,Mr. Edvard Pekoniemi,male,21.00,0,0,7.9250
115,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500
116,0,2,Mr. William John Robert Turpin,male,29.00,1,0,21.0000
117,0,1,Mr. Quigg Edmond Baxter,male,24.00,0,1,247.5208
118,0,3,Miss. Ellis Anna Maria Andersson,female,2.00,4,2,31.2750
119,0,2,Mr. Stanley George Hickman,male,21.00,2,0,73.5000
120,0,3,Mr. Leonard Charles Moore,male,19.00,0,0,8.0500
121,0,2,Mr. Nicholas Nasser,male,32.50,1,0,30.0708
122,1,2,Miss. Susan Webber,female,32.50,0,0,13.0000
123,0,1,Mr. Percival Wayland White,male,54.00,0,1,77.2875
124,1,3,Master. Elias Nicola-Yarred,male,12.00,1,0,11.2417
125,0,3,Mr. Martin McMahon,male,19.00,0,0,7.7500
126,1,3,Mr. Fridtjof Arne Madsen,male,24.00,0,0,7.1417
127,1,3,Miss. Anna Peter,female,2.00,1,1,22.3583
128,0,3,Mr. Johan Ekstrom,male,45.00,0,0,6.9750
129,0,3,Mr. Jozef Drazenoic,male,33.00,0,0,7.8958
130,0,3,Mr. Domingos Fernandeo Coelho,male,20.00,0,0,7.0500
131,0,3,Mrs. Alexander A (Grace Charity Laury) Robins,female,47.00,1,0,14.5000
132,1,2,Mrs. Leopold (Mathilde Francoise Pede) Weisz,female,29.00,1,0,26.0000
133,0,2,Mr. Samuel James Hayden Sobey,male,25.00,0,0,13.0000
134,0,2,Mr. Emile Richard,male,23.00,0,0,15.0458
135,1,1,Miss. Helen Monypeny Newsom,female,19.00,0,2,26.2833
136,0,1,Mr. Jacques Heath Futrelle,male,37.00,1,0,53.1000
137,0,3,Mr. Olaf Elon Osen,male,16.00,0,0,9.2167
138,0,1,Mr. Victor Giglio,male,24.00,0,0,79.2000
139,0,3,Mrs. Joseph (Sultana) Boulos,female,40.00,0,2,15.2458
140,1,3,Miss. Anna Sofia Nysten,female,22.00,0,0,7.7500
141,1,3,Mrs. Pekka Pietari (Elin Matilda Dolck) Hakkar...,female,24.00,1,0,15.8500
142,0,3,Mr. Jeremiah Burke,male,19.00,0,0,6.7500
143,0,2,Mr. Edgardo Samuel Andrew,male,18.00,0,0,11.5000
144,0,2,Mr. Joseph Charles Nicholls,male,19.00,1,1,36.7500
145,1,3,Mr. August Edvard Andersson,male,27.00,0,0,7.7958
146,0,3,Miss. Robina Maggie Ford,female,9.00,2,2,34.3750
147,0,2,Mr. Michel Navratil,male,36.50,0,2,26.0000
148,0,2,Rev. Thomas Roussel Davids Byles,male,42.00,0,0,13.0000
149,0,2,Rev. Robert James Bateman,male,51.00,0,0,12.5250
150,1,1,Mrs. Thomas (Edith Wearne) Pears,female,22.00,1,0,66.6000
151,0,3,Mr. Alfonzo Meo,male,55.50,0,0,8.0500
152,0,3,Mr. Austin Blyler van Billiard,male,40.50,0,2,14.5000
153,0,3,Mr. Ole Martin Olsen,male,27.00,0,0,7.3125
154,0,1,Mr. Charles Duane Williams,male,51.00,0,1,61.3792
155,1,3,Miss. Katherine Gilnagh,female,16.00,0,0,7.7333
156,0,3,Mr. Harry Corn,male,30.00,0,0,8.0500
157,0,3,Mr. Mile Smiljanic,male,37.00,0,0,8.6625
158,0,3,Master. Thomas Henry Sage,male,5.00,8,2,69.5500
159,0,3,Mr. John Hatfield Cribb,male,44.00,0,1,16.1000
160,1,2,Mrs. James (Elizabeth Inglis Milne) Watt,female,40.00,0,0,15.7500
161,0,3,Mr. John Viktor Bengtsson,male,26.00,0,0,7.7750
162,0,3,Mr. Jovo Calic,male,17.00,0,0,8.6625
163,0,3,Master. Eino Viljami Panula,male,1.00,4,1,39.6875
164,1,3,Master. Frank John William Goldsmith,male,9.00,0,2,20.5250
165,1,1,Mrs. (Edith Martha Bowerman) Chibnall,female,48.00,0,1,55.0000
166,0,3,Mrs. William (Anna Bernhardina Karlsson) Skoog,female,45.00,1,4,27.9000
167,0,1,Mr. John D Baumann,male,60.00,0,0,25.9250
168,0,3,Mr. Lee Ling,male,28.00,0,0,56.4958
169,0,1,Mr. Wyckoff Van der hoef,male,61.00,0,0,33.5000
170,0,3,Master. Arthur Rice,male,4.00,4,1,29.1250
171,1,3,Miss. Eleanor Ileen Johnson,female,1.00,1,1,11.1333
172,0,3,Mr. Antti Wilhelm Sivola,male,21.00,0,0,7.9250
173,0,1,Mr. James Clinch Smith,male,56.00,0,0,30.6958
174,0,3,Mr. Klas Albin Klasen,male,18.00,1,1,7.8542
175,0,3,Master. Henry Forbes Lefebre,male,5.00,3,1,25.4667
176,0,1,Miss. Ann Elizabeth Isham,female,50.00,0,0,28.7125
177,0,2,Mr. Reginald Hale,male,30.00,0,0,13.0000
178,0,3,Mr. Lionel Leonard,male,36.00,0,0,0.0000
179,0,3,Miss. Constance Gladys Sage,female,8.00,8,2,69.5500
180,0,2,Mr. Rene Pernot,male,39.00,0,0,15.0500
181,0,3,Master. Clarence Gustaf Hugo Asplund,male,9.00,4,2,31.3875
182,1,2,Master. Richard F Becker,male,1.00,2,1,39.0000
183,1,3,Miss. Luise Gretchen Kink-Heilmann,female,4.00,0,2,22.0250
184,0,1,Mr. Hugh Roscoe Rood,male,39.00,0,0,50.0000
185,1,3,Mrs. Thomas (Johanna Godfrey) O'Brien,female,26.00,1,0,15.5000
186,1,1,Mr. Charles Hallace Romaine,male,45.00,0,0,26.5500
187,0,3,Mr. John Bourke,male,40.00,1,1,15.5000
188,0,3,Mr. Stjepan Turcin,male,36.00,0,0,7.8958
189,1,2,Mrs. (Rosa) Pinsky,female,32.00,0,0,13.0000
190,0,2,Mr. William Carbines,male,19.00,0,0,13.0000
191,1,3,Miss. Carla Christine Nielsine Andersen-Jensen,female,19.00,1,0,7.8542
192,1,2,Master. Michel M Navratil,male,3.00,1,1,26.0000
193,1,1,Mrs. James Joseph (Margaret Tobin) Brown,female,44.00,0,0,27.7208
194,1,1,Miss. Elise Lurette,female,58.00,0,0,146.5208
195,0,3,Mr. Robert Mernagh,male,28.00,0,0,7.7500
196,0,3,Mr. Karl Siegwart Andreas Olsen,male,42.00,0,1,8.4042
197,1,3,Miss. Margaret Madigan,female,21.00,0,0,7.7500
198,0,2,Miss. Henriette Yrois,female,24.00,0,0,13.0000
199,0,3,Mr. Nestor Cyriel Vande Walle,male,28.00,0,0,9.5000
200,0,3,Mr. Frederick Sage,male,17.00,8,2,69.5500
201,0,3,Mr. Jakob Alfred Johanson,male,34.00,0,0,6.4958
202,0,3,Mr. Gerious Youseff,male,45.50,0,0,7.2250
203,1,3,Mr. Gurshon Cohen,male,18.00,0,0,8.0500
204,0,3,Miss. Telma Matilda Strom,female,2.00,0,1,10.4625
205,0,3,Mr. Karl Alfred Backstrom,male,32.00,1,0,15.8500
206,1,3,Mr. Nassef Cassem Albimona,male,26.00,0,0,18.7875
207,1,3,Miss. Helen Carr,female,16.00,0,0,7.7500
208,1,1,Mr. Henry Blank,male,40.00,0,0,31.0000
209,0,3,Mr. Ahmed Ali,male,24.00,0,0,7.0500
210,1,2,Miss. Clear Annie Cameron,female,35.00,0,0,21.0000
211,0,3,Mr. John Henry Perkin,male,22.00,0,0,7.2500
212,0,2,Mr. Hans Kristensen Givard,male,30.00,0,0,13.0000
213,0,3,Mr. Philip Kiernan,male,22.00,1,0,7.7500
214,1,1,Miss. Madeleine Newell,female,31.00,1,0,113.2750
215,1,3,Miss. Eliina Honkanen,female,27.00,0,0,7.9250
216,0,2,Mr. Sidney Samuel Jacobsohn,male,42.00,1,0,27.0000
217,1,1,Miss. Albina Bazzani,female,32.00,0,0,76.2917
218,0,2,Mr. Walter Harris,male,30.00,0,0,10.5000
219,1,3,Mr. Victor Francis Sunderland,male,16.00,0,0,8.0500
220,0,2,Mr. James H Bracken,male,27.00,0,0,13.0000
221,0,3,Mr. George Henry Green,male,51.00,0,0,8.0500
222,0,3,Mr. Christo Nenkoff,male,22.00,0,0,7.8958
223,1,1,Mr. Frederick Maxfield Hoyt,male,38.00,1,0,90.0000
224,0,3,Mr. Karl Ivar Sven Berglund,male,22.00,0,0,9.3500
225,1,2,Mr. William John Mellors,male,19.00,0,0,10.5000
226,0,3,Mr. John Hall Lovell,male,20.50,0,0,7.2500
227,0,2,Mr. Arne Jonas Fahlstrom,male,18.00,0,0,13.0000
228,0,3,Miss. Mathilde Lefebre,female,12.00,3,1,25.4667
229,1,1,Mrs. Henry Birkhardt (Irene Wallach) Harris,female,35.00,1,0,83.4750
230,0,3,Mr. Bengt Edvin Larsson,male,29.00,0,0,7.7750
231,0,2,Mr. Ernst Adolf Sjostedt,male,59.00,0,0,13.5000
232,1,3,Miss. Lillian Gertrud Asplund,female,5.00,4,2,31.3875
233,0,2,Mr. Robert William Norman Leyson,male,24.00,0,0,10.5000
234,0,3,Miss. Alice Phoebe Harknett,female,21.00,0,0,7.5500
235,0,2,Mr. Stephen Hold,male,44.00,1,0,26.0000
236,1,2,Miss. Marjorie Collyer,female,8.00,0,2,26.2500
237,0,2,Mr. Frederick William Pengelly,male,19.00,0,0,10.5000
238,0,2,Mr. George Henry Hunt,male,33.00,0,0,12.2750
239,0,3,Miss. Thamine Zabour,female,19.00,1,0,14.4542
240,1,3,Miss. Katherine Murphy,female,18.00,1,0,15.5000
241,0,2,Mr. Reginald Charles Coleridge,male,29.00,0,0,10.5000
242,0,3,Mr. Matti Alexanteri Maenpaa,male,22.00,0,0,7.1250
243,0,3,Mr. Sleiman Attalah,male,30.00,0,0,7.2250
244,0,1,Dr. William Edward Minahan,male,44.00,2,0,90.0000
245,0,3,Miss. Agda Thorilda Viktoria Lindahl,female,25.00,0,0,7.7750
246,1,2,Mrs. William (Anna) Hamalainen,female,24.00,0,2,14.5000
247,1,1,Mr. Richard Leonard Beckwith,male,37.00,1,1,52.5542
248,0,2,Rev. Ernest Courtenay Carter,male,54.00,1,0,26.0000
249,0,3,Mr. James George Reed,male,18.00,0,0,7.2500
250,0,3,Mrs. Wilhelm (Elna Matilda Persson) Strom,female,29.00,1,1,10.4625
251,0,1,Mr. William Thomas Stead,male,62.00,0,0,26.5500
252,0,3,Mr. William Arthur Lobb,male,30.00,1,0,16.1000
253,0,3,Mrs. Viktor (Helena Wilhelmina) Rosblom,female,41.00,0,2,20.2125
254,1,3,Mrs. Darwis (Hanne Youssef Razi) Touma,female,29.00,0,2,15.2458
255,1,1,Mrs. Gertrude Maybelle Thorne,female,38.00,0,0,79.2000
256,1,1,Miss. Gladys Cherry,female,30.00,0,0,86.5000
257,1,1,Miss. Anna Ward,female,35.00,0,0,512.3292
258,1,2,Mrs. (Lutie Davis) Parrish,female,50.00,0,1,26.0000
259,1,3,Master. Edvin Rojj Felix Asplund,male,3.00,4,2,31.3875
260,0,1,Mr. Emil Taussig,male,52.00,1,1,79.6500
261,0,1,Mr. William Harrison,male,40.00,0,0,0.0000
262,0,3,Miss. Delia Henry,female,21.00,0,0,7.7500
263,0,2,Mr. David Reeves,male,36.00,0,0,10.5000
264,0,3,Mr. Ernesti Arvid Panula,male,16.00,4,1,39.6875
265,1,3,Mr. Ernst Ulrik Persson,male,25.00,1,0,7.7750
266,1,1,Mrs. William Thompson (Edith Junkins) Graham,female,58.00,0,1,153.4625
267,1,1,Miss. Amelia Bissette,female,35.00,0,0,135.6333
268,0,1,Mr. Alexander Cairns,male,28.00,0,0,31.0000
269,1,3,Mr. William Henry Tornquist,male,25.00,0,0,0.0000
270,1,2,Mrs. (Elizabeth Anne Maidment) Mellinger,female,41.00,0,1,19.5000
271,0,1,Mr. Charles H Natsch,male,37.00,0,1,29.7000
272,1,3,Miss. Hanora Healy,female,33.00,0,0,7.7500
273,1,1,Miss. Kornelia Theodosia Andrews,female,63.00,1,0,77.9583
274,0,3,Miss. Augusta Charlotta Lindblom,female,45.00,0,0,7.7500
275,0,2,Mr. Francis Parkes,male,21.00,0,0,0.0000
276,0,3,Master. Eric Rice,male,7.00,4,1,29.1250
277,1,3,Mrs. Stanton (Rosa Hunt) Abbott,female,35.00,1,1,20.2500
278,0,3,Mr. Frank Duane,male,65.00,0,0,7.7500
279,0,3,Mr. Nils Johan Goransson Olsson,male,28.00,0,0,7.8542
280,0,3,Mr. Alfons de Pelsmaeker,male,16.00,0,0,9.5000
281,1,3,Mr. Edward Arthur Dorking,male,19.00,0,0,8.0500
282,0,1,Mr. Richard William Smith,male,57.00,0,0,26.0000
283,0,3,Mr. Ivan Stankovic,male,33.00,0,0,8.6625
284,1,3,Mr. Theodore de Mulder,male,30.00,0,0,9.5000
285,0,3,Mr. Penko Naidenoff,male,22.00,0,0,7.8958
286,1,2,Mr. Masabumi Hosono,male,42.00,0,0,13.0000
287,1,3,Miss. Kate Connolly,female,22.00,0,0,7.7500
288,1,1,Miss. Ellen Barber,female,26.00,0,0,78.8500
289,1,1,Mrs. Dickinson H (Helen Walton) Bishop,female,19.00,1,0,91.0792
290,0,2,Mr. Rene Jacques Levy,male,36.00,0,0,12.8750
291,0,3,Miss. Aloisia Haas,female,24.00,0,0,8.8500
292,0,3,Mr. Ivan Mineff,male,24.00,0,0,7.8958
293,0,1,Mr. Ervin G Lewy,male,30.00,0,0,27.7208
294,0,3,Mr. Mansour Hanna,male,23.50,0,0,7.2292
295,0,1,Miss. Helen Loraine Allison,female,2.00,1,2,151.5500
296,1,1,Mr. Adolphe Saalfeld,male,47.00,0,0,30.5000
297,1,1,Mrs. James (Helene DeLaudeniere Chaput) Baxter,female,50.00,0,1,247.5208
298,1,3,Miss. Anna Katherine Kelly,female,20.00,0,0,7.7500
299,1,3,Mr. Bernard McCoy,male,24.00,2,0,23.2500
300,0,3,Mr. William Cahoone Jr Johnson,male,19.00,0,0,0.0000
301,1,2,Miss. Nora A Keane,female,46.00,0,0,12.3500
302,0,3,Mr. Howard Hugh Williams,male,28.00,0,0,8.0500
303,1,1,Master. Hudson Trevor Allison,male,0.92,1,2,151.5500
304,1,1,Miss. Margaret Fleming,female,42.00,0,0,110.8833
305,1,1,Mrs. Victor de Satode (Maria Josefa Perez de S...,female,17.00,1,0,108.9000
306,0,2,Mr. Samuel Abelson,male,30.00,1,0,24.0000
307,1,1,Miss. Laura Mabel Francatelli,female,30.00,0,0,56.9292
308,1,1,Miss. Margaret Bechstein Hays,female,24.00,0,0,83.1583
309,1,1,Miss. Emily Borie Ryerson,female,18.00,2,2,262.3750
310,0,2,Mrs. William (Anna Sylfven) Lahtinen,female,26.00,1,1,26.0000
311,0,3,Mr. Ignjac Hendekovic,male,28.00,0,0,7.8958
312,0,2,Mr. Benjamin Hart,male,43.00,1,1,26.2500
313,1,3,Miss. Helmina Josefina Nilsson,female,26.00,0,0,7.8542
314,1,2,Mrs. Sinai (Miriam Sternin) Kantor,female,24.00,1,0,26.0000
315,0,2,Dr. Ernest Moraweck,male,54.00,0,0,14.0000
316,1,1,Miss. Mary Natalie Wick,female,31.00,0,2,164.8667
317,1,1,Mrs. Frederic Oakley (Margaretta Corning Stone...,female,40.00,1,1,134.5000
318,0,3,Mr. Samuel Dennis,male,22.00,0,0,7.2500
319,0,3,Mr. Yoto Danoff,male,27.00,0,0,7.8958
320,1,2,Miss. Hilda Mary Slayter,female,30.00,0,0,12.3500
321,1,2,Mrs. Albert Francis (Sylvia Mae Harbaugh) Cald...,female,22.00,1,1,29.0000
322,0,3,Mr. George John Jr Sage,male,20.00,8,2,69.5500
323,1,1,Miss. Marie Grice Young,female,36.00,0,0,135.6333
324,0,3,Mr. Johan Hansen Nysveen,male,61.00,0,0,6.2375
325,1,2,Mrs. (Ada E Hall) Ball,female,36.00,0,0,13.0000
326,1,3,Mrs. Frank John (Emily Alice Brown) Goldsmith,female,31.00,1,1,20.5250
327,1,1,Miss. Jean Gertrude Hippach,female,16.00,0,1,57.9792
328,1,3,Miss. Agnes McCoy,female,28.00,2,0,23.2500
329,0,1,Mr. Austen Partner,male,45.50,0,0,28.5000
330,0,1,Mr. George Edward Graham,male,38.00,0,1,153.4625
331,0,3,Mr. Leo Edmondus Vander Planke,male,16.00,2,0,18.0000
332,1,1,Mrs. Henry William (Clara Heinsheimer) Frauenthal,female,42.00,1,0,133.6500
333,0,3,Mr. Mitto Denkoff,male,30.00,0,0,7.8958
334,0,1,Mr. Thomas Clinton Pears,male,29.00,1,0,66.6000
335,1,1,Miss. Elizabeth Margaret Burns,female,41.00,0,0,134.5000
336,1,3,Mr. Karl Edwart Dahl,male,45.00,0,0,8.0500
337,0,1,Mr. Stephen Weart Blackwell,male,45.00,0,0,35.5000
338,1,2,Master. Edmond Roger Navratil,male,2.00,1,1,26.0000
339,1,1,Miss. Alice Elizabeth Fortune,female,24.00,3,2,263.0000
340,0,2,Mr. Erik Gustaf Collander,male,28.00,0,0,13.0000
341,0,2,Mr. Charles Frederick Waddington Sedgwick,male,25.00,0,0,13.0000
342,0,2,Mr. Stanley Hubert Fox,male,36.00,0,0,13.0000
343,1,2,Miss. Amelia Brown,female,24.00,0,0,13.0000
344,1,2,Miss. Marion Elsie Smith,female,40.00,0,0,13.0000
345,1,3,Mrs. Thomas Henry (Mary E Finck) Davison,female,34.00,1,0,16.1000
346,1,3,Master. William Loch Coutts,male,3.00,1,1,15.9000

In [9]:
# Restaurar configurações padrão de exibição de linhas e colunas
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

display(titanic_data)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [13]:
display(df)

     A    B
0  1.0  NaN
1  2.0  2.0
2  NaN  3.0
3  4.0  4.0

In [11]:
# Somando os valores de cada coluna (eixo 0, que é o padrão)
soma_colunas = df.sum()
display(soma_colunas)

A    7.0
B    9.0
dtype: float64

In [12]:
# Somando os valores de cada linha (eixo 1)
soma_linhas = df.sum(axis=1)
display(soma_linhas)

0    1.0
1    4.0
2    3.0
3    8.0
dtype: float64